apiVersion: v1
kind: ConfigMap
metadata:
  name: ecommerce-config
  namespace: ecommerce
data:
  SPRING_PROFILES_ACTIVE: "docker"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "ecommerce"
  MONGODB_URI: "mongodb://mongo:27017/ecommerce_audit"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
