# Uygulama Adı
spring.application.name=ecom-proj

# H2 Veritabanı Ayarları
spring.datasource.url=jdbc:h2:mem:EcommerceDB
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=project1

# H2 Konsolu (http://localhost:8080/h2-console adresinden veritabanını izlemek için)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Ayarları
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

# Dosya Yükleme Limitleri (Ürün Resimleri İçin)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# JWT Güvenlik Konfigürasyonu
app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
app.jwtExpirationMs=86400000

# Swagger / OpenAPI Dokümantasyon Yolları
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html